apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: hello-world
        image: koppula18/flask_helloworld
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        
---
apiVersion: v1
kind: Service
metadata:
  name: appdeploy
  labels:
    app: flask
spec:
  ports:
  - port: 4000
    protocol: TCP
    name: flask
  selector:
    app: flask
  type: LoadBalancer